### PR TITLE
fix(types): improve TypeScript strict typing for numeric keys in HttpStatus

### LINKED ISSUE #48: Unable to properly infer numeric keys in TypeScript type with mixed key types
**Describe the bug**

When utilizing the `http-status` package, there is a bug related to inferring numeric keys in TypeScript when working with a mixed type declaration within the `HttpStatus` interface in [index.d.ts](https://github.com/adaltas/node-http-status/blame/71a991bc4efa131985e97e35248f41bb59c62e6b/lib/index.d.ts).

**To Reproduce**

To reproduce the issue, consider the following TypeScript code snippet:

```typescript
import httpStatus from "http-status"; // object itself
import type { HttpStatus } from "http-status"; // interface

// example for comparison
const testStatus = {
  100: "",
  "100_NAME": "",
  "100_MESSAGE": "",
  CONTINUE: 100,
  101: "",
  "101_NAME": "",
  "101_MESSAGE": "",
  SWITCHING_PROTOCOLS: 101,
  102: "",
  "102_NAME": "",
  "102_MESSAGE": "",
  PROCESSING: 102,
  103: "",
  "103_NAME": "",
  "103_MESSAGE": "",
  EARLY_HINTS: 103,
};

// Define a custom type to extract numeric keys
type NumberKeys<T> = {
  [K in keyof T]: T[K] extends number ? (string extends K ? never : K) : never;
}[keyof T];

// Define a function with a parameter that should only accept numeric keys
export function Response(code: NumberKeys<HttpStatus>) {
  const thisCode = httpStatus[code];
  // Rest of your function logic
}
```

In this case, the types do not work correctly and autocompletion does show any possible string in the ide 
image

When changing the type input to the example object:

```diff
- export function Response(code: NumberKeys<HttpStatus>) {
+ export function Response(code: NumberKeys<typeof test>) {
    const thisCode = httpStatus[code];
    // Rest of your function logic
  }
```

it then works and shows the correct types

image

Additionally, the unnecessary declaration `readonly [key: number]: string | undefined;` in the `HttpStatus` interface contributes to the issue and might be impacting TypeScript type inference.

**Additional context**

The issue seems to be associated with the mixed type declaration within the `HttpStatus` interface  in [index.d.ts](https://github.com/adaltas/node-http-status/blame/71a991bc4efa131985e97e35248f41bb59c62e6b/lib/index.d.ts), specifically:

```typescript
export = httpStatus;

declare const httpStatus: httpStatus.HttpStatus;

declare namespace httpStatus {
  interface HttpStatus {
    // not important for this issue, but I still see no sense in this either
    readonly [key: number]: string | undefined;

    // this causes the issue
    readonly [key: string]:
    | string
    | number
    | HttpStatusClasses
    | HttpStatusExtra
    | undefined;
```

This declaration allows for both string and number keys, leading to unexpected behavior in TypeScript type inference. The bug impacts TypeScript type inference in projects utilizing the `http-status` package, particularly when trying to enforce strict typing for numeric keys. The unnecessary `readonly [key: number]` declaration are causing the issue and should be considered for removal.

### PR DESCRIPTION
**Pull request by aronmal**
The TypeScript type inference for numeric keys in the HttpStatus interface was previously unspecific, causing issues in strict typing scenarios. This fix removes unnecessary declarations, ensuring more accurate and strict TypeScript typing for numeric keys. It also includes updates to unit tests to reflect and validate the improved strict typing.

Closes #48

### CODE REVIEW

File: test/types.ts [hunk 1]
```diff
@@ -50,32 +41,32 @@ describe('Types', () => {
   describe('ES6 exports', () => {
 
     it('HttpStatus', () => {
-      const statuses: HttpStatus = status
```
Comment (wdavidw) [inline test/types.ts:53]: Why are you removing the type cast to HttpStatus ? I believe we shall keep those (same question for the tests below)

Comment (aronmal) [reply test/types.ts:53]: Because they are now implicitly inferred.

Do you wish them to stay?

Comment (aronmal) [reply test/types.ts]: I just reworked it. It now only has necessary changes.

**Comment by aronmal** [comment]
Unit test now has only necessary changes.
